version: "3.8"

services:
  portainer:
    image: portainer/portainer-ee:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443"
      # -"9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - public

volumes:
  portainer_data:

networks:
  public:
    external: true